-- Add the property fields used by the current capture form and MLS views.
-- All changes are additive; existing property rows remain intact.
alter table public.properties
  add column if not exists purpose text not null default 'venda',
  add column if not exists accepts_trade boolean not null default false,
  add column if not exists trade_details text,
  add column if not exists condition text not null default 'usado',
  add column if not exists hotel_rooms_count integer,
  add column if not exists useful_area_m2 numeric(8, 2),
  add column if not exists total_area_m2 numeric(8, 2),
  add column if not exists solar_position text,
  add column if not exists view_type text,
  add column if not exists property_age integer,
  add column if not exists iptu_period text default 'anual',
  add column if not exists documentation_status text,
  add column if not exists accepts_financing boolean not null default true,
  add column if not exists private_amenities jsonb not null default '[]'::jsonb,
  add column if not exists condo_amenities jsonb not null default '[]'::jsonb,
  add column if not exists garage_type text default 'coberta',
  add column if not exists cep text,
  add column if not exists state text,
  add column if not exists street text,
  add column if not exists street_number text,
  add column if not exists block text,
  add column if not exists floor text,
  add column if not exists condo_name text,
  add column if not exists hide_street boolean not null default false,
  add column if not exists video_url text,
  add column if not exists cover_photo text,
  add column if not exists floor_plan_photos jsonb not null default '[]'::jsonb;
